### ISSUE TITLE
Need to have the the projects page as the landing page temporarily for all members of the Wakehurst team

### ISSUE THREAD

**Issue by jeremyreffin** [wearepal/landscapes#128]
This is a suggested temporary but fast fix for dealing with the fact that the site at the moment is a mess of pages from the old and new versions etc. We definitely should not be wasting any time right now sorting that out - a suggested temporary fix is that we direct to the following landing page: https://landscapes.wearepal.ai/teams/4/projects

This can perhaps just be done manually by telling everyone to use that as the landing page for now.

**Comment by olliethomas** [comment]
Linked to #274 - This should be resolved by that "in the wash"
