### ISSUE TITLE
Implement "evaluate expression" node type in old modelling tool

### ISSUE THREAD

**Issue by olliethomas** [wearepal/landscapes#246]
We want a new node type that allows the user to choose from a predefined list of expressions (e.g. `a^2 + 3 * b - c`) from a dropdown menu.

First we should find a suitable Javascript library that can parse & evaluate expressions.

The node should automatically have 1 numeric input for each variable (`a`, `b`, `c` in the example above), and 1 numeric output.

When the model is run, the node should compute the value of the expression for each tile.

**Comment by olliethomas** [comment]
> James Robinson [16 Dec 2022 at 15:41](https://trello.com/c/kr37RuGg/203-implement-evaluate-expression-node-type-in-old-modelling-tool#comment-639c919b4a9cdc007c488715)
Waiting for some real expressions/equations to hardcode into the app before deploying this

**Comment by olliethomas** [comment]
> Paul Crossley [21 Aug 2023 at 13:49](https://trello.com/c/kr37RuGg/203-implement-evaluate-expression-node-type-in-old-modelling-tool#comment-64e35d4c72046c4701b9c254)
Added to new modelling tool. Don’t have a current need for it in the old right now.

**Comment by paulthatjazz** [comment]
Closing this issue as we no longer work on the old modelling tool.
