### ISSUE TITLE
add a `/legacy` url and put the old app on that

### ISSUE THREAD

**Issue by olliethomas** [wearepal/landscapes#274]

**Comment by olliethomas** [comment]
@nquadrianto do we know where the old app is currently being linked from?

**Comment by olliethomas** [comment]
If we don't want to change the url, because the "old" app _has_ to remain at landscapes.wearepal.ai, then maybe we could instead make the current app available at lmt.wearepal.ai? Or use wearepal.ai/lmt to redirect to a better landing page than the "old" app?

**Comment by olliethomas** [comment]
i spoke with jonathon - he's happy for either there to be a link at the bottom of the "new" page, linking to the "old" app. He still also has 'edit' access to the report he produced, so can update links in his publications that reference the old app.

**Comment by paulthatjazz** [comment]
Created the `/legacy` url. Old logic still applies for now while we test.
