### ISSUE TITLE
Taking a complement set operation flips the booleans on the masked area

### ISSUE THREAD

**Issue by jeremyreffin** [wearepal/landscapes#378]
**Describe the bug**
If you have chosen a shape extent (e.g. Wealden District Council) then the areas outside the extent should always be excluded. However the Complement set operation flips the bits in the masked out area.

**To Reproduce**
1. Choose an extent like WDC
2. Take a boolean feature from some input (e.g. coniferous woodland)
3. Apply the Complement operation
4. The result will show TRUE bits for the area outside the extent

**Expected behavior**
Area outside the extent should always be ignored

**Screenshots**
Attached
<img width="933" alt="Screenshot 2024-06-05 at 11 12 52" src="https://github.com/wearepal/landscapes/assets/4549944/e3b18751-e5b0-4c74-85cc-f62d4c53e463">

**Comment by paulthatjazz** [comment]
Attached PR should deal with the issue. 

Creating a new issue to refactor the performOperation worker to incorporate the masks when we have more time to deal with tech debt. This should consider the mask within the operation instead of applying the mask after to improve efficiency.
