### ISSUE TITLE
Manually drawing a new larger extent (after using a pre-defined extent) breaks the model

### ISSUE THREAD

**Issue by jeremyreffin** [wearepal/landscapes#384]
**Describe the bug**
If you manually select as extent a (larger) area manually, after you have been using a pre-defined extent, the model no longer works at all. The model runs but shows empty set results. e.g. IMD claims no data.

**To Reproduce**
1. Go to Species comp test - NBN Atlas data - Wealden
2. Run with Wealdon
3. Change extent manually and run again

**Expected behavior**
It should work when you change the extent

**Screenshots**
IMD - no data found
![image](https://github.com/wearepal/landscapes/assets/4549944/d28f0489-3d16-4463-8ca7-8ce7efca8446)

**Comment by paulthatjazz** [comment]
Likely due to the mask data still existing when updating the extent. I have an idea how to fix this.
